---
mito:
    seg: 
        pipeline: 
            AC: 
                scaling_param: [0,18]
            G2:
                sigma: 1
            F2: 
                f2_param: [[1.2,0.16]]
            S:
                min_size: 15
                connectivity: 1
        ops: 
            inplace: False

peroxy:
    seg: 
        pipeline: 
            AC: 
                scaling_param: [0,20]
            G2:
                sigma: 1
            S2: 
                s2_param: [[1.8 ,0.03]]
            WD: {}
            S:
                min_size: 10
                connectivity: 1
        ops: 
            inplace: False

er:
    seg:
        pipeline:
            AC:
                scaling_param: [0.5,11]
            ES:
                niter: 2
                kappa: 1.2
            F2:
                f2_param: [[1.4,0.14]]
            S:
                min_size: 20
                connectivity: 1
        ops: 
            inplace: False

golgi: 
    seg:
        pipeline:
            AC:
                scaling_param: [2,20]
            G2:
                sigma: 1
            or_branch:
                branch1:
                    MO:
                        global_thresh_method: tri
                        object_minArea: 1200
#                     TT: 
#                         min_thickness: 1.6
#                         thin: 1
                branch2:
                    S2:
                        s2_param:
            S:
                min_size: 20
                connectivity: 1
        ops: 
            inplace: False

lyso:
    seg:
        pipeline:
            AC: 
                scaling_param: [0,17]
            G2:
                sigma: 1
            or_branch:
                branch1:
                    S2:
                        s2_param: [[6,0.15], [3,0.05]]
                branch2:
                    F2:
                        [[1.6, 0.2]]
            HF:
                hole_min: 0
                hole_max: 1200
            S:
                min_size: 20
                connectivity: 1
        ops: 
            inplace: False
            
            
            